#!/bin/bash

REPO="securityonionsolutions"

# Create a directory for our Docker images
mkdir images
cd images

# Pull down docker images and save to .tar files 
for i in so-elasticsearch so-kibana so-logstash so-elastalert so-freqserver so-domainstats so-curator; do
	docker pull --disable-content-trust=false $REPO/$i
	docker save $REPO/$i > $i.tar
done
